services:
  - type: web
    name: sde-webapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
